# Site
title: Oficina Oito

# URL
url: https://oficinaoito.com
baseurl: ''
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4663
future: false

# Data
social:
  instagram: "https://www.instagram.com/oficinaoito"
  facebook: "https://www.facebook.com/oficinaoito"
  twitter: ""
  flickr: ""
  github: ""
  youtube: ""
  vimeo: ""
  soundcloud: ""
  tumblr: ""
  pinterest: ""
  envelope-o: "mailto:oi@oficinaoito.com"
twitter_user: "OficinaOito"

# prose.io
prose:
  media: 'media/images'
  ignore:
    - .gitignore
    - _config.yml
    - _includes
    - _layouts
    - _sass
    - css
    - js
    - CNAME
    - media/favicons
    - media/swipebox
